// This file was generated by Prisma
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    // Use direct process.env to skip validation at build time
    // Railway will provide DATABASE_URL at runtime
    url: process.env.DATABASE_URL ?? "postgresql://placeholder",
  },
});