// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SentryRegistry$Type } from "./SentryRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SentryRegistry"]: SentryRegistry$Type;
    ["contracts/SentryRegistry.sol:SentryRegistry"]: SentryRegistry$Type;
  }

  interface ContractTypesMap {
    ["SentryRegistry"]: GetContractReturnType<SentryRegistry$Type["abi"]>;
    ["contracts/SentryRegistry.sol:SentryRegistry"]: GetContractReturnType<SentryRegistry$Type["abi"]>;
  }
}
